import type { Draft, Metrics, Overview, PilotSummary, Recommendation, Simulation, Workflow } from "../src/api/schemas";

export const context = { fictional_data: true as const, organisation: "Northstar Clinics", declaration: "Fictional Northstar Clinics administrative data", artefact_fingerprint: "abc123" };
export const overview: Overview = { context, proposition: "Discover workflow bottlenecks safely.", workflow_summary: "A fictional referral workflow.", metrics: [{ key: "cases", label: "Cases", value: 1000, unit: "cases", note: null }], journey: ["Events", "Evidence", "Review"], bottleneck: "Completeness", opportunity: "Review", simulation_result: "No guaranteed benefit", pilot_assessment: "ready_for_fictional_pilot_demo", authority: ["No message sent"] };
export const workflow: Workflow = { context, nodes: [{ id: "a", label: "Referral received", frequency: 1000, manual_work_rate: 0, stage: "Intake", x: 0, y: 0 }, { id: "b", label: "Completeness checked", frequency: 1000, manual_work_rate: 1, stage: "Validation", x: 200, y: 0 }], edges: [{ id: "a-b", source: "a", target: "b", frequency: 1000, median_delay_hours: 17.8, handoff: false, rework: false, bottleneck: true }], variants: [{ id: "variant-one", case_count: 800, activities: ["Referral received", "Completeness checked"], median_duration_hours: 20, outcome: "completed" }], strict: { model: "strict", fully_conforming_rate: 0.36, average_fitness: 0.92, interpretation: "Strict" }, governed: { model: "governed", fully_conforming_rate: 0.87, average_fitness: 0.99, interpretation: "Governed" }, complexity: [{ key: "nodes", label: "Activities", value: 2, unit: "count", note: null }], filters: { service_lines: ["All", "Neurology"], referral_sources: ["All", "GP practice"] } };
const series = { key: "completeness", label: "First-pass completeness", unit: "%", status: "estimated" as const, denominator: 100, values: [{ cohort: "GP practice", case_count: 50, value: 51.8 }] };
export const metrics: Metrics = { context, overall: [{ key: "duration", label: "Duration", value: 226, unit: "hours", note: null }], referral_sources: [series], service_lines: [series], quality: [{ label: "Availability", value: 98, unit: "%", status: "calculated" }], findings: [{ title: "Lower completeness", cohort: "GP practice", observed: "51.8%", comparison: "67.8% overall", materiality: "material" }], exclusions: ["Clinical analysis excluded."] };
export const simulation: Simulation = { context, scenarios: ["conservative", "central", "optimistic", "adverse"].map((id, index) => ({ id: id as Simulation["scenarios"][number]["id"], affected_cases: 20 + index, review_overhead_hours: 10, fallbacks: 5, failures: 2, net_burden_hours: id === "optimistic" ? 4 : -2, decision: id === "optimistic" ? "Shadow only" : "Do not act", metrics: [{ key: "manual", label: "Manual touches", baseline: 7.2, simulated: 6.9, unit: "per case" }] })), selected_scenario: "central", finding: "Review overhead mattered.", caveats: ["Not realised impact."] };
export const recommendation: Recommendation = { recommendation_id: "pilot-rec-123", detector_evaluation_id: "eval", case_id: "00000000-0000-4000-8000-000000000001", snapshot_id: "snapshot", detected_at: "2026-07-19T09:00:00Z", missing_field_ids: ["supporting_document"], source_references: ["source-event"], requirement_references: ["supporting-document"], detector_product_name: "completeness-review-detector-v1", supported_detector_fingerprint: "supported", original_detector_fingerprint: "original", current: true, unresolved_source_conflict: false, recommendation_only: true };
export const draft: Draft = { draft_id: "draft-123", recommendation_id: recommendation.recommendation_id, case_id: recommendation.case_id, administrative_recipient_role: "fictional_referring_organisation_admin", form_version: "v2", source_snapshot_references: ["source-event"], requirements_contract_references: ["supporting-document"], created_at: "2026-07-19T09:00:00Z", expires_at: "2026-07-19T17:00:00Z", status: "draft_awaiting_review", current_revision_id: "revision-1", revisions: [{ revision_id: "revision-1", previous_revision_id: null, editor_role: "system", revised_at: "2026-07-19T09:00:00Z", change_reason: "initial_deterministic_template", changed_fields: ["heading", "body"], heading: "Administrative information review", body: "Supporting document confirmation. Human review is required.", items: [{ field_id: "supporting_document", display_name: "Supporting document confirmation", requirement_id: "supporting-document" }], audit_reference: "audit-ref" }], human_review_required: true, no_message_sent: true, fictional_declaration: "Fictional pilot" };
export const pilotSummary: PilotSummary = { run_id: "run", policy_version: "policy-v1", detector_name: "completeness-review-detector-v1", detector_lineage: "strict-v3", assessment: "ready_for_fictional_pilot_demo", metrics: { incoming_cases: 120, detector_positives: 29, detector_positive_coverage: 0.24, detector_precision: 0.966, detector_recall: 0.8, recommendations_entering_pilot: 12, surfaced_recommendation_coverage: 0.1, drafts_created: 12, drafts_reviewed: 3, drafts_edited: 1, drafts_approved: 2, drafts_rejected: 1, fictional_tasks_committed: 2, rollbacks: 1, review_minutes: 12, unresolved_drafts: 9, policy_compliance: 1, audit_completeness: 1, rollback_success_rate: 1, external_communication_attempts: 0, operational_workflow_mutations: 0 }, gates: [], fictional_declaration: "Fictional pilot", no_message_sent: true };

